version: "3.8"

services:
  web:
    container_name: aarchid-api
    image: dfordp/sarnet-api/service-api
    env_file:
      - .env
    ports:
      - "8082:8082"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpass123
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    depends_on:
      - web
  redis:
    container_name: redis-stack-server
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    depends_on:
      - web

volumes:
  postgres_data: